In [2]:
import pandas as pd
import numpy as np
folder = 'd:/git/project1/generated'

In [5]:
df = pd.read_csv(f'{folder}/bts_price_changes.csv')
del df['Unnamed: 0']
df = df.drop(index=[2400])

Open          High           Low         Close        Volume  \
0       465.864014    468.174011    452.421997    457.334015  2.105680e+07   
1       456.859985    456.859985    413.104004    424.440002  3.448320e+07   
2       424.102997    427.834991    384.532013    394.795990  3.791970e+07   
3       394.673004    423.295990    389.882996    408.903992  3.686360e+07   
4       408.084991    412.425995    393.181000    398.821014  2.658010e+07   
...            ...           ...           ...           ...           ...   
2396  58253.777344  61276.664063  58038.707031  59793.234375  5.823847e+10   
2397  59846.230469  60790.554688  59289.796875  60204.964844  4.628025e+10   
2398  60175.945313  61253.035156  59589.875000  59893.453125  5.182869e+10   
2399  60292.875000  63152.812500  59892.859375  62944.847656  6.289527e+10   
2400    451.837402    451.837402    451.837402    451.837402  4.678324e+10   

      change_1_day  change_3_day  change_7_day  change_14_day  change_30_day  \
0         0.000000      0.000000      0.000000       0.000000       0.000000   
1        -9.004029      0.000000      0.000000       0.000000       0.000000   
2       -32.756988      0.000000      0.000000       0.000000       0.000000   
3       -29.429993    -71.191010      0.000000       0.000000       0.000000   
4        13.411987    -48.774994      0.000000       0.000000       0.000000   
...            ...           ...           ...            ...            ...   
2396   2226.648437   -845.371094   -772.316406    6643.550781    3502.550781   
2397    -72.785156     67.269531  -1143.632812    3116.210938    2290.597656   
2398   1592.453125   3746.316406   2241.390625    3871.289063    2025.011719   
2399    329.714844   1849.382813   1415.070313    4228.046875    2832.574219   
2400    116.929687   2039.097656   1120.941406    2542.742187    -928.257813   

      change_60_day  change_90_day  change_180_day   timestamp  
0          0.000000       0.000000        0.000000  1410912000  
1          0.000000       0.000000        0.000000  1410998400  
2          0.000000       0.000000        0.000000  1411084800  
3          0.000000       0.000000        0.000000  1411171200  
4          0.000000       0.000000        0.000000  1411257600  
...             ...            ...             ...         ...  
2396   19439.734375   17537.921875    47030.480469  1618012800  
2397   12068.785156   17999.558594    58120.811523  1618099200  
2398   13376.468750   21499.699219    48550.148438  1618185600  
2399   15277.234375   24659.585938    48746.897461  1618272000  
2400   12415.839844   26377.753906    48866.272461  1587168000  

[2401 rows x 14 columns]

In [73]:
period = 180
df[f'change_percent_{period}'] = df.apply(lambda x: x[f'change_{period}_day']/x['Close'], axis=1)
target = f'change_percent_{period}'
df[['timestamp', 'Open', 'High', 'Low', 'Close', 'Volume', target]].corr()[target].sort_values()

timestamp             0.066710
Volume                0.108482
Low                   0.159527
Close                 0.161598
Open                  0.162195
High                  0.163327
change_percent_180    1.000000
Name: change_percent_180, dtype: float64

In [116]:
df.to_csv(f'{folder}/bts_price_changes.csv')

In [58]:
x_train = np.array(df.loc[:1800,['timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']])
x_train

array([[1.41091200e+09, 4.65864014e+02, 4.68174011e+02, 4.52421997e+02,
        4.57334015e+02, 2.10568000e+07],
       [1.41099840e+09, 4.56859985e+02, 4.56859985e+02, 4.13104004e+02,
        4.24440002e+02, 3.44832000e+07],
       [1.41108480e+09, 4.24102997e+02, 4.27834991e+02, 3.84532013e+02,
        3.94795990e+02, 3.79197000e+07],
       ...,
       [1.56625920e+09, 1.09163467e+04, 1.09470420e+04, 1.06189609e+04,
        1.07632324e+04, 1.50530822e+10],
       [1.56634560e+09, 1.07645723e+04, 1.07987295e+04, 9.96272168e+03,
        1.01380498e+04, 1.94730848e+10],
       [1.56643200e+09, 1.01425215e+04, 1.02329961e+04, 9.83146289e+03,
        1.01310557e+04, 1.70975089e+10]])

In [93]:
target = f'direct_{period}'
y_train = np.array(df.loc[:1800,[target]])
y_train

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [87]:
x_test = np.array(df.loc[1801:,['timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']])
x_test

array([[1.56651840e+09, 1.01363096e+04, 1.04424434e+04, 1.00781924e+04,
        1.04079648e+04, 1.56270239e+10],
       [1.56660480e+09, 1.04076445e+04, 1.04180205e+04, 9.98229688e+03,
        1.01599609e+04, 1.54510306e+10],
       [1.56669120e+09, 1.01607373e+04, 1.03046221e+04, 1.00087891e+04,
        1.01385176e+04, 1.41538566e+10],
       ...,
       [1.61809920e+09, 5.98462305e+04, 6.07905547e+04, 5.92897969e+04,
        6.02049648e+04, 4.62802526e+10],
       [1.61818560e+09, 6.01759453e+04, 6.12530352e+04, 5.95898750e+04,
        5.98934531e+04, 5.18286885e+10],
       [1.61827200e+09, 6.02928750e+04, 6.31528125e+04, 5.98928594e+04,
        6.29448477e+04, 6.28952719e+10]])

In [94]:
y_test = np.array(df.loc[1801:,[target]])
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [96]:
%%time
parameters = {'C': np.linspace(0.0001, 100, 20)}
grid_search = GridSearchCV(LogisticRegression(), parameters)
grid_search.fit(x_train, y_train.ravel())

print('best parameters: ', grid_search.best_params_)
print('best scrores: ', grid_search.best_score_)

best parameters:  {'C': 0.0001}
best scrores:  0.5707710064635273
Wall time: 1.63 s


In [98]:
%%time
clf = LogisticRegression(C=0.0001)
clf.fit(x_train, y_train.ravel())

Wall time: 24 ms


LogisticRegression(C=0.0001)

In [76]:
LinearRegression().get_params().keys()

dict_keys(['copy_X', 'fit_intercept', 'n_jobs', 'normalize', 'positive'])

In [99]:
clf.score(x_test, y_test)

0.7161936560934892

In [102]:
from sklearn.dummy import DummyClassifier
clf_dummy = DummyClassifier()

scores = cross_val_score(clf_dummy, x_test, y_test)
print("Dummy classifier score: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Dummy classifier score: 0.716 (+/- 0.00)


In [103]:
from sklearn.ensemble import RandomForestRegressor


In [106]:
%%time
rf = RandomForestRegressor(n_estimators = 1000)
rf.fit(x_train, y_train.ravel())

Wall time: 5.58 s


RandomForestRegressor(n_estimators=1000)

In [107]:
rf_pred = rf.predict(x_test)

In [108]:
threshold = 0.5
preds = [1 if val > threshold else 0 for val in rf_pred]

In [110]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score

In [114]:
#print(roc_auc_score(preds, y_test))
print(confusion_matrix(preds, y_test))
print(accuracy_score(preds, y_test))

[[  0   0]
 [170 429]]
0.7161936560934892
